[RA-55] UI for Restaurants and Users screens
georgedobrev/Restaurant_Assistant pull request #30
Opened 2023-06-07 06:23 UTC by valentinArnautski

2023-06-08 10:26 UTC, betinabp requested changes

2023-06-08 10:26 UTC, betinabp commented on Front-end/Restauran Web/src/screens/admin/Restaurant/data.tsx
> +const rows = [
Create an interface for the data and set the type for rows.

2023-06-08 10:26 UTC, betinabp commented on Front-end/Restauran Web/src/screens/admin/Restaurant/restaurant.module.css
> +  margin: 4px 0 6px 0;
You are mixing %, rem and pixel. Please choose one and stick to it for consistency.

2023-06-08 10:26 UTC, betinabp commented on Front-end/Restauran Web/src/screens/admin/Users/Users.tsx
> +const Users = (): JSX.Element => {
Remove `JSX.Element`. Typescript will detect the return type implicitly. Rather than that set type for const Users. 
<img width="756" alt="image" src="https://github.com/georgedobrev/Restaurant_Assistant/assets/131862675/1a21de87-43c9-46c4-8748-16e7384d7e30">

2023-06-08 10:26 UTC, betinabp commented on Front-end/Restauran Web/src/screens/admin/Users/Users.tsx
> +const Users = (): JSX.Element => {
Please add type for all components!

2023-06-08 10:26 UTC, betinabp commented on Front-end/Restauran Web/src/screens/admin/Restaurant/AddRestaurant.tsx
> +            style={{
Avoid using inline styles! Create a class for this.

2023-06-09 06:36 UTC, valentinArnautski commented on Front-end/Restauran Web/src/screens/admin/Restaurant/AddRestaurant.tsx
> +        <div className={styles["flex-column"]}>
I use this syntax className={styles["flex-column"]} for class names that include a "-" in their names.

2023-06-09 08:04 UTC, betinabp commented on Front-end/Restauran Web/src/screens/admin/Restaurant/AddRestaurant.tsx
> +            style={{ background: "var(--primary-color)" }}
Move this to the class.

2023-06-09 08:06 UTC, betinabp commented on Front-end/Restauran Web/src/screens/admin/Users/mockData.tsx
> +interface rowsRestaurant {
Interfaces always start with upper case.

2023-06-09 08:07 UTC, betinabp commented on Front-end/Restauran Web/src/screens/admin/Users/DataGrid.tsx
> +const gridColumns = (
Components always start with uppercase

2023-06-09 08:07 UTC, betinabp commented on Front-end/Restauran Web/src/screens/admin/Users/DataGrid.tsx
> +  onButtonClick: (e: React.MouseEvent<HTMLButtonElement>, row: any) => void
Add type for row. Do you even need it?

2023-06-09 08:08 UTC, betinabp commented on Front-end/Restauran Web/src/screens/admin/Users/DataGrid.tsx
> +    renderCell: (params) => {
Add type for params

2023-06-09 11:12 UTC, betinabp approved these changes

2023-06-09 11:12 UTC, merged