RA-99 Improve restaurant details
georgedobrev/Restaurant_Assistant pull request #60
Opened 2023-06-19 12:11 UTC by hristiyanaSh

2023-06-19 16:07 UTC, mkanevv reviewed
Има да се доизпипа, моля те като си ги пускаш PR-ите, преглеждай ги и ти преди мен

2023-06-19 16:07 UTC, mkanevv commented on Backend/Restaurant/src/main/java/com/blankfactor/ra/model/Restaurant.java
>      private String name;
дали отговаря с базата?

2023-06-19 16:07 UTC, mkanevv commented on Backend/Restaurant/src/main/java/com/blankfactor/ra/repository/AppTableRepository.java
> +    int countByRestaurantId(int restaurantId);
нека да е Интеджер

2023-06-19 16:07 UTC, mkanevv commented on Backend/Restaurant/src/main/java/com/blankfactor/ra/service/AppTableService.java
> +import org.checkerframework.checker.units.qual.A;
? май това не ни трябва

2023-06-19 16:07 UTC, mkanevv commented on Backend/Restaurant/src/main/java/com/blankfactor/ra/service/RestaurantService.java
>      Restaurant getRestaurantById(Integer restaurantId) throws Exception;
не хвърлят правилния ексепшън

2023-06-19 16:07 UTC, mkanevv commented on Backend/Restaurant/src/main/java/com/blankfactor/ra/service/impl/AppTableServiceImpl.java
> +        int tablesCount = appTableRepository.findByRestaurantId(restaurantId).size();//appTables.size();
нещо тук не е правилно с логиката, помисли си

2023-06-19 16:07 UTC, mkanevv commented on Backend/Restaurant/src/main/java/com/blankfactor/ra/service/impl/RestaurantServiceImpl.java
> +    }
не се нуждаем ве§е от този метод май

2023-06-19 18:32 UTC, hristiyanaSh commented on Backend/Restaurant/src/main/java/com/blankfactor/ra/service/impl/RestaurantServiceImpl.java
> +    }
Ами не, ползвам го в updateRestaurantById

2023-06-19 18:45 UTC, hristiyanaSh commented on Backend/Restaurant/src/main/java/com/blankfactor/ra/model/Restaurant.java
>      private String name;
има column "name" в restaurant table, да

2023-06-23 10:29 UTC, mkanevv commented on Backend/Restaurant/pom.xml
> +        </dependency>
тези май не ни трябват

2023-06-28 15:17 UTC, mkanevv requested changes
ще ги адресираш ли коментарите

2023-06-30 09:42 UTC, mkanevv approved these changes

2023-06-30 09:42 UTC, merged