[RA-168] Tables Sections
georgedobrev/Restaurant_Assistant pull request #89
Opened 2023-07-05 07:28 UTC by valentinArnautski

<img width="960" alt="Screenshot 2023-07-05 at 10 27 45" src="https://github.com/georgedobrev/Restaurant_Assistant/assets/131446923/6c339176-47f6-4bb5-8421-ac66b8f81fcc">

2023-07-05 11:21 UTC, betinabp requested changes

2023-07-05 11:21 UTC, betinabp commented on Front-end/Restauran Web/src/screens/admin/sections/AddSectionButtons.tsx
> +  const handleChange = (event: any) => {
Add type to event

2023-07-05 11:21 UTC, betinabp commented on Front-end/Restauran Web/src/screens/admin/sections/AddSectionButtons.tsx
> +      target: { value },
This can be done on row 26. You don't need to create another variable. 
It will be like `({target: {value}}: SetTheTypeHere)`

2023-07-05 11:21 UTC, betinabp commented on Front-end/Restauran Web/src/screens/admin/sections/TableSections.tsx
> +  const [sections, setSections] = useState<any[]>([]);
Use the interface for sections instead of any.

2023-07-05 11:21 UTC, betinabp commented on Front-end/Restauran Web/src/screens/admin/restaurants/DisplayRestaurants.tsx
> +    const isRestaurantSelected = restaurants.some(
Why do you use some here? Don't you want to check if the current selected restaurant has property isSelected=true?

2023-07-06 09:00 UTC, valentinArnautski commented on Front-end/Restauran Web/src/screens/admin/restaurants/DisplayRestaurants.tsx
> +    const isRestaurantSelected = restaurants.some(
When the user selects a restaurant the storedRestaurantID on the local storage gets updated and in this case only 1 restaurant can be selected. So I use some to check if any of the restaurants is selected and then redirect the user to the next page. 

<img width="948" alt="Screenshot 2023-07-06 at 11 50 40" src="https://github.com/georgedobrev/Restaurant_Assistant/assets/131446923/834e5113-1460-4bb6-a239-4f59ff17ed0a">

2023-07-06 09:11 UTC, betinabp approved these changes

2023-07-06 09:12 UTC, merged